module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
baseURL: "https://blog-kevinlupera.netlify.app/"
title: Kevin
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kevin
  description: "Kevin Dev"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon16x16.ico"
    favicon32x32: "/favicon32x32.ico"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Kevin Lupera
    subtitle: "I'm **Full Stack developer** finish program at the **University Hemisferios**, Ecuador 🇪🇨. 
      Backend engineer 🧑🏻💻 at **[Alegra](http://www.alegra.com/)**, a SaaS based in Colombia 🇨🇴. 
      Computer Systems Engineer in Ecuador 🇪🇨 at the **University of Guayaquil**. 
      I'm passionate about experimenting with **DIY projects** and interested in cloud computing."
    imageUrl: 'profile.jpeg'
    imageWidth: 120
    imageHeight: 120
    imageTitle: Profile
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: medium
      url: "https://kevin13k.medium.com/"
    - name: github
      url: "https://github.com/kevinlupera"
    - name: gitlab
      url: "https://gitlab.com/kevinlupera"
    - name: linkedin
      url: "https://www.linkedin.com/in/kevin-lupera/"
    - name: email
      url: "mailito:kevinlupera@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 20
    - identifier: project
      name: Projects
      url: /projects/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: experiences
      name: Experience
      url: /experiences/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
